import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

/**
 * Paystack billing state, mirrored locally.
 *
 * The Autumn build did not need this: one `customers.get(userId)` returned
 * subscriptions, purchases and invoices, so entitlement could be resolved by
 * asking the provider on every request. Paystack has no equivalent — its
 * customers are keyed by its own `customer_code`, there is no
 * "subscriptions for my application's user id" lookup, and cancellation
 * requires an `email_token` that is only ever handed out once, at the moment
 * the subscription is created.
 *
 * So this is the authority for "what has this person paid for", and Paystack
 * is the authority for "did this payment happen". Every row here is written
 * only after a transaction was verified against Paystack's API by reference —
 * never from a webhook body alone, and never from anything the client said.
 *
 * The practical consequences, all deliberate:
 *
 *   - entitlement resolution is a local indexed read, so a Paystack outage
 *     cannot log out every paying learner
 *   - a renewal, a failed charge or a cancellation only lands here when its
 *     webhook does, so the webhook endpoint is load-bearing and its delivery
 *     failures matter (hence `paystack_events`, which makes replay safe)
 *   - `email_token` must be captured on sight or cancel/resume is impossible
 */

const now = sql`(unixepoch())`;

/**
 * Paystack's five subscription states, kept verbatim rather than flattened to
 * a boolean.
 *
 * The Autumn integration collapsed everything to active/not and had no way to
 * express "their card failed" — so a subscriber whose payment bounced saw a
 * working Premium account until the day it silently vanished. `attention` is
 * the state that gap lived in, and it is stored and surfaced for that reason.
 */
export const PAYSTACK_STATUSES = [
  /** Live and renewing. */
  "active",
  /** Live, paid up, but will not renew — a cancellation awaiting period end. */
  "non-renewing",
  /** Live, but the last charge FAILED. Retried on the next payment date. */
  "attention",
  /** Ran to completion. No further charges, no further access after `until`. */
  "completed",
  /** Stopped. */
  "cancelled",
] as const;
export type PaystackStatus = (typeof PAYSTACK_STATUSES)[number];

/** Statuses that still entitle the holder to the tier they paid for. */
export const ENTITLING_STATUSES: readonly PaystackStatus[] = [
  "active",
  "non-renewing",
  // Deliberately entitling. The period has been paid for; the failure is the
  // NEXT charge. Cutting access the instant a renewal declines punishes the
  // most common cause — an expired card on an otherwise willing customer —
  // and Paystack will retry on the next payment date. Access ends when the
  // paid period ends, which is what `until` already enforces.
  "attention",
];

/**
 * One Paystack customer per app user.
 *
 * Paystack deduplicates customers by email, so `POST /customer` is idempotent
 * and this table is a cache rather than a ledger. It is still worth keeping:
 * it saves a round trip on every checkout, and it records which Paystack
 * identity a user's payments belong to even if they later change their email
 * in the app.
 */
export const paystackCustomers = sqliteTable(
  "paystack_customers",
  {
    userId: text("user_id").primaryKey(),
    customerCode: text("customer_code").notNull(),
    /** The address the Paystack customer was created under, lowercased. */
    email: text("email").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [index("idx_paystack_customer_code").on(t.customerCode)],
);

/**
 * Every checkout this app has started, and what became of it.
 *
 * Written before the customer leaves for Paystack, so an abandoned checkout is
 * visible as an abandoned checkout rather than as nothing at all — which is
 * the difference between "our payment page is broken" and "nobody clicked
 * buy", and the Autumn build could answer neither.
 *
 * The `reference` is generated by us, not Paystack, so it can be tied to a
 * user and an option before any money moves, and so a duplicate submission
 * lands on the same reference instead of opening a second charge.
 */
export const paystackCheckouts = sqliteTable(
  "paystack_checkouts",
  {
    /** Our own reference, also Paystack's transaction reference. */
    reference: text("reference").primaryKey(),
    userId: text("user_id").notNull(),
    /** The BILLING_OPTIONS id, e.g. "premium_annual". */
    optionId: text("option_id").notNull(),
    /** Resolved tier, copied so a later price-list edit cannot rewrite history. */
    plan: text("plan").notNull(),
    term: text("term").notNull(),
    /** Subunit (cents). What we asked Paystack to charge. */
    amountSubunit: integer("amount_subunit").notNull(),
    currency: text("currency").notNull(),
    /**
     * Nullable only because the column has always been. Every option sold is a
     * subscription and therefore carries a plan code; a null here on a new row
     * is a bug, not a one-off purchase.
     */
    planCode: text("plan_code"),
    status: text("status")
      .$type<"pending" | "success" | "failed" | "abandoned">()
      .notNull()
      .default("pending"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
    /** When a verification confirmed this one way or the other. */
    settledAt: integer("settled_at", { mode: "timestamp" }),
  },
  (t) => [
    index("idx_paystack_checkout_user").on(t.userId, t.createdAt),
    index("idx_paystack_checkout_status").on(t.status),
  ],
);

/**
 * A paid entitlement. Every one of them is a recurring subscription.
 *
 * `recurring` and a nullable `until` are historical: a withdrawn one-off
 * purchase (`premium_lifetime`) once wrote rows with `recurring: false`, no
 * subscription code and a null `until`, and two test-mode rows in that shape
 * still exist. Nothing writes them any more, and the entitling read in
 * `store.ts` grants nothing for a row without an `until` — a paid row with no
 * end date is treated as broken rather than as permanent access.
 *
 * The columns are kept rather than migrated away because they hold rows that
 * represent real money, and a migration over payment history to tidy a shape
 * is a bad trade.
 */
export const paystackSubscriptions = sqliteTable(
  "paystack_subscriptions",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    /** The BILLING_OPTIONS id this was bought as. */
    optionId: text("option_id").notNull(),
    plan: text("plan").notNull(),
    term: text("term").notNull(),
    recurring: integer("recurring", { mode: "boolean" }).notNull(),
    /**
     * Paystack's subscription code. Null only on the withdrawn one-off rows;
     * every row written now has one, and without it cancel cannot work.
     */
    subscriptionCode: text("subscription_code"),
    /**
     * Paystack's per-subscription token, required with the code to disable or
     * re-enable it. Issued once and never re-fetchable in isolation, so it is
     * stored the first time it is seen. Without it, cancel does not work.
     */
    emailToken: text("email_token"),
    planCode: text("plan_code"),
    status: text("status").$type<PaystackStatus>().notNull(),
    /**
     * End of the period already paid for, ms since epoch. Also the next charge
     * date for a live subscription; the UI must read `status` to know which it
     * is showing. Null grants nothing — see the table comment above.
     */
    until: integer("until", { mode: "timestamp_ms" }),
    amountSubunit: integer("amount_subunit").notNull(),
    currency: text("currency").notNull(),
    /** The transaction reference that created this. Ties a grant to a receipt. */
    reference: text("reference"),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [
    index("idx_paystack_sub_user").on(t.userId, t.status),
    // One row per Paystack subscription, so a replayed `subscription.create`
    // updates the existing grant instead of granting a second one. Partial on
    // NOT NULL because one-off purchases legitimately share a NULL code, and
    // SQLite treats every NULL as distinct in a plain unique index anyway.
    uniqueIndex("uq_paystack_sub_code")
      .on(t.subscriptionCode)
      .where(sql`${t.subscriptionCode} is not null`),
    // The same one-off charge must not be fulfilled twice either.
    uniqueIndex("uq_paystack_sub_reference")
      .on(t.reference)
      .where(sql`${t.reference} is not null`),
  ],
);

/**
 * Receipts, as Paystack reports them.
 *
 * Kept locally because Paystack's transaction list is account-wide and paged;
 * asking it for "this user's payments" means filtering someone else's data
 * client-side. One row per successful charge, written by the same fulfilment
 * path that writes the grant.
 */
export const paystackPayments = sqliteTable(
  "paystack_payments",
  {
    /** Paystack's transaction reference. */
    reference: text("reference").primaryKey(),
    userId: text("user_id").notNull(),
    optionId: text("option_id"),
    amountSubunit: integer("amount_subunit").notNull(),
    currency: text("currency").notNull(),
    status: text("status").notNull(),
    /** "card", "bank", ... — what they actually paid with. */
    channel: text("channel"),
    paidAt: integer("paid_at", { mode: "timestamp_ms" }),
    /** True when taken with a test key, so test payments never read as revenue. */
    testMode: integer("test_mode", { mode: "boolean" }).notNull().default(false),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(now),
  },
  (t) => [index("idx_paystack_payment_user").on(t.userId, t.paidAt)],
);

/**
 * Webhook events already processed, so processing one twice is a no-op.
 *
 * Paystack retries a webhook it did not get a 200 for, and will re-send the
 * same event; `charge.success` in particular arrives both as a webhook and as
 * the redirect return, and both paths fulfil. Without this table a renewal
 * could extend a period twice, or a retried delivery could re-grant a
 * cancelled plan.
 *
 * Keyed on a hash of the raw body rather than an event id, because Paystack's
 * payloads carry no delivery id — `data.id` repeats across the event types
 * that describe one transaction.
 */
export const paystackEvents = sqliteTable(
  "paystack_events",
  {
    /** SHA-256 of the raw request body, hex. */
    id: text("id").primaryKey(),
    event: text("event").notNull(),
    /** The transaction or subscription reference this concerned, when it had one. */
    reference: text("reference"),
    receivedAt: integer("received_at", { mode: "timestamp" }).notNull().default(now),
    /** Null when handled cleanly; the error text when it was not. */
    error: text("error"),
  },
  (t) => [index("idx_paystack_event_type").on(t.event, t.receivedAt)],
);
