/**
 * Audio cache.
 *
 * Course content is fixed: the 250 vocabulary items, 44 dialogue lines and 6
 * pronunciation drills never change between learners, so synthesizing them
 * once and reusing the clip is both cheaper and faster than a live call per
 * tap. Only free-form tutor replies go straight to the provider.
 *
 * The key deliberately includes the *normalized* text, not the raw text: two
 * source strings that normalize identically should share one clip, and any
 * change to the text pipeline must invalidate the cache rather than keep
 * serving audio generated by the old rules.
 */

import { createHash } from "node:crypto";
import { and, desc, eq, sql } from "drizzle-orm";
import { db } from "../database";
import * as s from "../database/schema";
import type { VoiceMode } from "./ssml";

/** Clips larger than this are served but not stored, to keep rows sane. */
const MAX_CACHED_BYTES = 1_500_000;

export type CacheKeyInput = {
  provider: string;
  voice: string;
  mode: VoiceMode;
  normalizedText: string;
};

export function cacheKey(input: CacheKeyInput): string {
  return createHash("sha256")
    .update(`${input.provider}|${input.voice}|${input.mode}|${input.normalizedText}`)
    .digest("hex");
}

export type CachedAudio = {
  id: string;
  mimeType: string;
  audio: Uint8Array;
  durationMsEstimate: number | null;
};

export async function readCache(id: string): Promise<CachedAudio | null> {
  const [row] = await db.select().from(s.speechAudio).where(eq(s.speechAudio.id, id));
  if (!row?.audioBase64) return null;

  // Best-effort hit counter: a failed increment must never fail playback.
  await db
    .update(s.speechAudio)
    .set({ hits: sql`${s.speechAudio.hits} + 1` })
    .where(eq(s.speechAudio.id, id))
    .catch(() => undefined);

  return {
    id: row.id,
    mimeType: row.mimeType,
    audio: Uint8Array.from(Buffer.from(row.audioBase64, "base64")),
    durationMsEstimate: row.durationMsEstimate,
  };
}

export type WriteCacheInput = CacheKeyInput & {
  sourceText: string;
  mimeType: string;
  audio: Uint8Array;
  durationMsEstimate: number;
  kind?: string;
  refId?: string | null;
};

export async function writeCache(input: WriteCacheInput): Promise<string> {
  const id = cacheKey(input);
  if (input.audio.byteLength > MAX_CACHED_BYTES) return id;

  await db
    .insert(s.speechAudio)
    .values({
      id,
      provider: input.provider,
      voice: input.voice,
      mode: input.mode,
      sourceText: input.sourceText,
      normalizedText: input.normalizedText,
      mimeType: input.mimeType,
      audioBase64: Buffer.from(input.audio).toString("base64"),
      byteLength: input.audio.byteLength,
      durationMsEstimate: input.durationMsEstimate,
      kind: input.kind ?? "ad_hoc",
      refId: input.refId ?? null,
    })
    .onConflictDoNothing();

  return id;
}

/** What is cached for one content item, so the UI can show real coverage. */
export async function coverage(kind: string) {
  const rows = await db
    .select({
      refId: s.speechAudio.refId,
      mode: s.speechAudio.mode,
      voice: s.speechAudio.voice,
    })
    .from(s.speechAudio)
    .where(and(eq(s.speechAudio.kind, kind), sql`${s.speechAudio.refId} is not null`));
  return rows;
}

export async function cacheStats() {
  const [row] = await db
    .select({
      clips: sql<number>`count(*)`,
      bytes: sql<number>`coalesce(sum(${s.speechAudio.byteLength}), 0)`,
      hits: sql<number>`coalesce(sum(${s.speechAudio.hits}), 0)`,
    })
    .from(s.speechAudio);

  const recent = await db
    .select({
      id: s.speechAudio.id,
      sourceText: s.speechAudio.sourceText,
      voice: s.speechAudio.voice,
      mode: s.speechAudio.mode,
      kind: s.speechAudio.kind,
    })
    .from(s.speechAudio)
    .orderBy(desc(s.speechAudio.createdAt))
    .limit(10);

  return {
    clips: Number(row?.clips ?? 0),
    bytes: Number(row?.bytes ?? 0),
    hits: Number(row?.hits ?? 0),
    recent,
  };
}
